url:         http://www.vonavi.me
title:       Редактор на стероидах
description: O редакторе GNU Emacs, ОС Linux, движке Jekyll и не только
imgdir:      http://dl.dropbox.com/u/35307988/www.vonavi.me/images
googleplus:  https://plus.google.com/106537166685709212154

destination: public
permalink:   pretty
paginate:    5                  # the number of post per page

exclude:    ['Gemfile*', 'README', 'vendor']
keep_files: ['.gitkeep']

encoding: UTF-8

# Default site configuration
defaults:
  - scope:
      path: ru
      type: pages
    values:
      layout: default

  - scope:
      path: ru
      type: posts
    values:
      layout:   post
      comments: true

  - scope:
      path: ru
      type: drafts
    values:
      layout:   post
      comments: false
