url:         http://www.vonavi.me
title:       Редактор на стероидах
description: O редакторе GNU Emacs, ОС Linux, движке Jekyll и не только
imgdir:      http://dl.dropbox.com/u/35307988/www.vonavi.me/images
googleplus:  https://plus.google.com/106537166685709212154

destination: public
permalink:   pretty
paginate:    5                  # the number of post per page

exclude:    ['Gemfile*', 'README', 'vendor']
keep_files: ['.gitkeep']
gems:       ['jekyll-assets']

encoding: UTF-8

#
# Plugin: jekyll-assets
#
assets:
  #
  # Sets compressors. No compression by default.
  #
  compress:
    js:  yui
    css: yui
